import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { TRPCReactProvider } from "@/trpc/react"; // 不再直接使用
import { Providers } from "./providers"; // 导入新的 Providers 组件

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
